language: elixir
elixir:
  - 1.8.1
env:
  - MIX_ENV=test
services:
  - postgresql
cache:
  directories:
    - _build
    - deps
    - apps/the_tavern_web/assets/node_modules
notifications:
  email: false
jobs:
  include:
    - stage: "Compile"
      script:
        - mix do ecto.create, ecto.migrate
        - mix compile
        - mix check
    - stage: "Test"
      script: mix test
