language: elixir
elixir:
  - 1.8.1

env:
  - MIX_ENV=test CYPRESS_CACHE_FOLDER=.cache

addons:
  postgresql: "9.4"

services:
  - postgresql

before_script:
  - cp config/travis_test.exs config/test.exs
  - cp config/travis_prod.exs config/prod.exs
  - mix do ecto.create, ecto.migrate
  - MIX_ENV=prod mix do ecto.create, ecto.migrate

script:
  - mix check
  - mix test
  - (cd e2e && npm install)
  - (cd apps/the_tavern_web && npm install --prefix assets && npm run deploy --prefix assets)
  - MIX_ENV=prod mix phx.server &
  - (cd e2e && npm test)
  - kill $(jobs -p) || true

notifications:
  email: false
