language: elixir
elixir:
  - 1.8.1

env:
  - MIX_ENV=test CYPRESS_CACHE_FOLDER=.cache

addons:
  postgresql: "9.4"

services:
  - postgresql

cache:
  directories:
    - _build
    - deps
    - apps/the_tavern_web/assets/node_modules
    - e2e/node_modules
    - e2e/.cache

before_script:
  - cp config/travis_test.exs config/test.exs
  - cp config/travis_prod.exs config/prod.exs

jobs:
  include:
    - stage: "Build"
      script:
        - bin/travis/build.sh
        - mix check
    - stage: "Test"
      script: mix test
      name: "Unit Tests"
    - script:
        - MIX_ENV=prod bin/travis/build.sh
        - MIX_ENV=prod bin/travis/e2e.sh
      name: "E2E Tests"

notifications:
  email: false
