language: elixir
elixir:
  - 1.8.1

env:
  - MIX_ENV=test CYPRESS_CACHE_FOLDER=.cache

addons:
  postgresql: "9.4"

services:
  - postgresql

cache:
  directories:
    - _build
    - deps
    - apps/the_tavern_web/assets/node_modules
    - e2e/node_modules
    - e2e/.cache

before_script:
  - cp config/travis_test.exs config/test.exs
  - cp config/travis_prod.exs config/prod.exs

jobs:
  include:
    - stage: "Build"
      script:
        - mix compile
        - mix check
        - mix do ecto.create, ecto.migrate
    - stage: "Test"
      script: mix test
      name: "Unit Tests"
    - script:
        - MIX_ENV=prod mix do ecto.create, ecto.migrate
        - (cd e2e && npm install)
        - (cd apps/the_tavern_web && npm install --prefix assets && npm run deploy --prefix assets)
        - MIX_ENV=prod mix phx.server &
        - (cd e2e && npm test)
        - kill $(jobs -p) || true
      name: "E2E Tests"

notifications:
  email: false
